{
    "width": 44,
    "height": 32,
    "chars": [
        {
            "name": "Unnamed Character",
            "sched": {
                "0": {
                    "type": "static",
                    "x": 11,
                    "y": 12
                },
                "195": {
                    "type": "linear",
                    "x": 18,
                    "y": 14,
                    "cx1": 240,
                    "cy1": 216
                },
                "360": {
                    "type": "linear",
                    "x": 5,
                    "y": 24,
                    "cx1": 192,
                    "cy1": 312
                },
                "915": {
                    "type": "linear",
                    "x": 40,
                    "y": 5,
                    "cx1": 368,
                    "cy1": 240
                },
                "1080": {
                    "type": "quadratic",
                    "x": 15,
                    "y": 15,
                    "cx1": 554,
                    "cy1": 345
                }
            }
        },
        {
            "name": "Unnamed Character",
            "sched": {
                "0": {
                    "type": "static",
                    "x": 23,
                    "y": 10
                },
                "195": {
                    "type": "linear",
                    "x": 19,
                    "y": 14,
                    "cx1": 344,
                    "cy1": 200
                },
                "360": {
                    "type": "quadratic",
                    "x": 24,
                    "y": 31,
                    "cx1": 203,
                    "cy1": 444
                },
                "915": {
                    "type": "linear",
                    "x": 13,
                    "y": 1,
                    "cx1": 304,
                    "cy1": 264
                }
            }
        },
        {
            "name": "Unnamed Character",
            "sched": {
                "0": {
                    "type": "static",
                    "x": 24,
                    "y": 18
                },
                "195": {
                    "type": "linear",
                    "x": 20,
                    "y": 14,
                    "cx1": 360,
                    "cy1": 264
                },
                "360": {
                    "type": "linear",
                    "x": 36,
                    "y": 3,
                    "cx1": 456,
                    "cy1": 144
                },
                "1080": {
                    "type": "linear",
                    "x": 6,
                    "y": 27,
                    "cx1": 344,
                    "cy1": 248
                }
            }
        }
    ]
}